TRUNCATE TABLE REGIONALI;

INSERT ALL
    INTO REGIONALI (ID_REGIONAL, NUME, PRENUME, EMAIL, NR_TEL) VALUES (1, 'Ambrus', 'Ramona', 'ramona.ambrus@hypermarket.ro', '0770 660 837')
    INTO REGIONALI (ID_REGIONAL, NUME, PRENUME, EMAIL, NR_TEL) VALUES (2, 'Taranu', 'Nicu', 'nicu.taranu@hypermarket.ro', '0770 660 838')
    INTO REGIONALI (ID_REGIONAL, NUME, PRENUME, EMAIL, NR_TEL) VALUES (3, 'Stan', 'Ion', 'ion.stan@hypermarket.ro', '0770 660 839')
    INTO REGIONALI (ID_REGIONAL, NUME, PRENUME, EMAIL, NR_TEL) VALUES (4, 'Calin', 'Cristian', 'cristian.calin@hypermarket.ro', '0770 660 840')
    INTO REGIONALI (ID_REGIONAL, NUME, PRENUME, EMAIL, NR_TEL) VALUES (5, 'Florea', 'Bob', 'bob.florea@hypermarket.ro', '0770 660 841')
    SELECT * FROM DUAL;


TRUNCATE TABLE MAGAZINE;

INSERT ALL
    INTO MAGAZINE (ID_MAGAZIN, ID_REGIONAL, ORAS, NUME_MAGAZIN, ADRESA) VALUES (1, 1, 'Bucuresti', 'Pallady', 'Aleea Veveritelor 10')
    INTO MAGAZINE (ID_MAGAZIN, ID_REGIONAL, ORAS, NUME_MAGAZIN, ADRESA) VALUES (2, 2, 'Bucuresti', 'Militari', 'Strada Zumzetelor 67')
    INTO MAGAZINE (ID_MAGAZIN, ID_REGIONAL, ORAS, NUME_MAGAZIN, ADRESA) VALUES (3, 2, 'Timisoara', 'Timisoara 1', 'Strada Cohleelor 69')
    INTO MAGAZINE (ID_MAGAZIN, ID_REGIONAL, ORAS, NUME_MAGAZIN, ADRESA) VALUES (4, 3, 'Timisoara', 'Timisoara 2', 'Strada Pamfletelor 12')
    INTO MAGAZINE (ID_MAGAZIN, ID_REGIONAL, ORAS, NUME_MAGAZIN, ADRESA) VALUES (5, 4, 'Arad', 'Arad 1', 'Strada Coriandrului 16')
    SELECT * FROM DUAL;

INSERT ALL
    INTO DEPARTAMENTE (ID_DEPARTAMENT, NUME, BUGET) VALUES (10, 'HR', 60000)
    INTO DEPARTAMENTE (ID_DEPARTAMENT, NUME, BUGET) VALUES (20, 'Peste', 70000)
    INTO DEPARTAMENTE (ID_DEPARTAMENT, NUME, BUGET) VALUES (30, 'Legume si Fructe', 30000)
    INTO DEPARTAMENTE (ID_DEPARTAMENT, NUME, BUGET) VALUES (40, 'Carne', 65000)
    INTO DEPARTAMENTE (ID_DEPARTAMENT, NUME, BUGET) VALUES (50, 'Intretinere', 90000)
    INTO DEPARTAMENTE (ID_DEPARTAMENT, NUME, BUGET) VALUES (60, 'Livrari', 91000)
    INTO DEPARTAMENTE (ID_DEPARTAMENT, NUME, BUGET) VALUES (70, 'Vanzari', 55100)
    INTO DEPARTAMENTE (ID_DEPARTAMENT, NUME, BUGET) VALUES (80, 'Contabilitate', 110000)
SELECT * FROM DUAL;

INSERT ALL
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (1, 10)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (1, 20)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (1, 30)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (1, 40)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (1, 50)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (2, 40)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (2, 50)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (2, 60)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (2, 70)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (2, 80)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (2, 30)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (3, 10)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (3, 20)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (4, 10)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (4, 60)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (5, 80)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (5, 70)
    INTO DEPARTAMENTE_MAGAZIN (ID_MAGAZIN, ID_DEPARTAMENT) VALUES (5, 60)
SELECT * FROM DUAL;

INSERT ALL
    INTO ANGAJATI (ID_ANGAJAT, ID_MAGAZIN, ID_DEPARTAMENT, NUME, PRENUME, FUNCTIE, ACTIV, SALARIU)
    VALUES (6101000, 1, 20, 'Mocanu', 'Andreea', 'Manager', 1, 10000)
    INTO ANGAJATI (ID_ANGAJAT, ID_MAGAZIN, ID_DEPARTAMENT, NUME, PRENUME, FUNCTIE, ACTIV, SALARIU)
    VALUES (6101001, 2, 30, 'Burdan', 'Maia', 'Consilier Vanzari Senior', 1, 3500)
    INTO ANGAJATI (ID_ANGAJAT, ID_MAGAZIN, ID_DEPARTAMENT, NUME, PRENUME, FUNCTIE, ACTIV, SALARIU)
    VALUES (6101002, 2, 30, 'Avasiloae', 'Alex', 'Consilier Vanzari Expert', 1, 6000)
    INTO ANGAJATI (ID_ANGAJAT, ID_MAGAZIN, ID_DEPARTAMENT, NUME, PRENUME, FUNCTIE, ACTIV, SALARIU)
    VALUES (6101003, 1, 10, 'Corin', 'Alin', 'Specialist People and Culture', 1, 10000)
    INTO ANGAJATI (ID_ANGAJAT, ID_MAGAZIN, ID_DEPARTAMENT, NUME, PRENUME, FUNCTIE, ACTIV, SALARIU)
    VALUES (6101004, 1, 20, 'Voros', 'Darius', 'Consilier Vanzari Senior', 0, 3600)
    INTO ANGAJATI (ID_ANGAJAT, ID_MAGAZIN, ID_DEPARTAMENT, NUME, PRENUME, FUNCTIE, ACTIV, SALARIU)
    VALUES (6101005, 1, 20, 'Croea', 'Cloe', 'Consilier Vanzari Senior', 1, 3700)
SELECT * FROM DUAL;

INSERT ALL
    INTO ECHIPE (ID_ECHIPA, NUME, NR_TEL)
    VALUES (1, 'Helpdesk', '0770 660 333')
    INTO ECHIPE (ID_ECHIPA, NUME, NR_TEL)
    VALUES (2, 'RBC', '0770 660 334')
    INTO ECHIPE (ID_ECHIPA, NUME, NR_TEL)
    VALUES (3, 'SIBS', '0770 660 335')
    INTO ECHIPE (ID_ECHIPA, NUME, NR_TEL)
    VALUES (4, 'ClickServ', '0770 660 336')
    INTO ECHIPE (ID_ECHIPA, NUME, NR_TEL)
    VALUES (5, 'User Services', '0770 660 337')
SELECT * FROM DUAL;

INSERT ALL
    INTO UPSURI (ID_UPS, ID_MAGAZIN, ACTIV)
    VALUES (12001, 1, 1)
    INTO UPSURI (ID_UPS, ID_MAGAZIN, ACTIV)
    VALUES (12002, 2, 1)
    INTO UPSURI (ID_UPS, ID_MAGAZIN, ACTIV)
    VALUES (12003, 3, 1)
    INTO UPSURI (ID_UPS, ID_MAGAZIN, ACTIV)
    VALUES (12004, 4, 1)
    INTO UPSURI (ID_UPS, ID_MAGAZIN, ACTIV)
    VALUES (12005, 5, 1)
SELECT * FROM DUAL;

INSERT ALL
    INTO CASE_MARCAT(ID_CASA, ID_MAGAZIN, NUMAR_CASA, ADRESA_IP, REZERVA)
    VALUES (1, 1, 10, '10.216.1.10', 0)
    INTO CASE_MARCAT(ID_CASA, ID_MAGAZIN, NUMAR_CASA, ADRESA_IP, REZERVA)
    VALUES (2, 1, 11, '10.216.1.11', 0)
    INTO CASE_MARCAT(ID_CASA, ID_MAGAZIN, NUMAR_CASA, ADRESA_IP, REZERVA)
    VALUES (3, 1, 52, '10.216.1.52', 1)
    INTO CASE_MARCAT(ID_CASA, ID_MAGAZIN, NUMAR_CASA, ADRESA_IP, REZERVA)
    VALUES (4, 2, 11, '10.216.2.11', 0)
    INTO CASE_MARCAT(ID_CASA, ID_MAGAZIN, NUMAR_CASA, ADRESA_IP, REZERVA)
    VALUES (5, 2, 12, '10.216.2.12', 0)
    INTO CASE_MARCAT(ID_CASA, ID_MAGAZIN, NUMAR_CASA, ADRESA_IP, REZERVA)
    VALUES (6, 3, 10, '10.216.3.10', 0)
    INTO CASE_MARCAT(ID_CASA, ID_MAGAZIN, NUMAR_CASA, ADRESA_IP, REZERVA)
    VALUES (7, 4, 10, '10.216.4.10', 0)
    INTO CASE_MARCAT(ID_CASA, ID_MAGAZIN, NUMAR_CASA, ADRESA_IP, REZERVA)
    VALUES (8, 5, 10, '10.216.5.10', 0)
SELECT * FROM DUAL;

INSERT ALL
    INTO DOCUMENTE (ID_DOCUMENT, NUME, LOCATIE, DIMENSIUNE, FORMAT_DOC)
    VALUES (1, 'mesaj', './docs', 5, '.msg')
    INTO DOCUMENTE (ID_DOCUMENT, NUME, LOCATIE, DIMENSIUNE, FORMAT_DOC)
    VALUES (2, 'mesaj(1)', './docs', 3, '.msg')
    INTO DOCUMENTE (ID_DOCUMENT, NUME, LOCATIE, DIMENSIUNE, FORMAT_DOC)
    VALUES (3, 'aafc', './docs', 8, '.docx')
    INTO DOCUMENTE (ID_DOCUMENT, NUME, LOCATIE, DIMENSIUNE, FORMAT_DOC)
    VALUES (4, 'poza_scanner', './images', 1, '.jpg')
    INTO DOCUMENTE (ID_DOCUMENT, NUME, LOCATIE, DIMENSIUNE, FORMAT_DOC)
    VALUES (5, 'video_casa10', './docs', 10, '.mp4')
SELECT * FROM DUAL;

INSERT ALL
    INTO TICHETE(ID_TICHET, ID_ANGAJAT, ID_ECHIPA, ID_MAGAZIN, ID_CASA, ID_DOCUMENT, TITLU, DESCRIERE, CATEGORIE,
    STATUS_TICHET)
    VALUES(1, 6101000, 1, 1, 1, 1, 'Ajutor', 'Nu mai merge casa 10', 'Case de marcat', 'In lucru')
    INTO TICHETE(ID_TICHET, ID_ANGAJAT, ID_ECHIPA, ID_MAGAZIN, ID_UPS, TITLU, DESCRIERE, CATEGORIE,
    STATUS_TICHET, PRIORITATE)
    VALUES(2, 6101001, 1, 2, 12002, 'UPS down', 'UPS From STORE Militari (ID 2) is not responding to pings', 'UPS', 'In lucru', 1)
    INTO TICHETE(ID_TICHET, ID_ANGAJAT, ID_ECHIPA, ID_MAGAZIN, ID_CASA, ID_DOCUMENT, TITLU, DESCRIERE, CATEGORIE,
    STATUS_TICHET)
    VALUES(3, 6101000, 2, 1, 2, 2, 'Casa 11 nefunctionala', 'Nu mai merge casa 11', 'Case de marcat', 'In lucru')
    INTO TICHETE(ID_TICHET, ID_ANGAJAT, ID_ECHIPA, ID_MAGAZIN, ID_CASA, ID_DOCUMENT, TITLU, DESCRIERE, CATEGORIE,
    STATUS_TICHET)
    VALUES(4, 6101005, 1, 1, 1, 1, 'Casa 10 nefunctionala!!!', 'Casa 10 s-a stricat :C', 'Case de marcat', 'Rezolvat')
    INTO TICHETE(ID_TICHET, ID_ECHIPA, ID_MAGAZIN, ID_UPS, TITLU, DESCRIERE, CATEGORIE,
    STATUS_TICHET, PRIORITATE)
    VALUES(5, 1, 2, 12002, 'UPS down', 'UPS From STORE Militari (ID 2) is not responding to pings', 'UPS', 'Rezolvat', 1)
SELECT * FROM DUAL;

COMMIT;